name: mortgage_exp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^7.1.0
  get_it: ^7.2.0
  logger: ^1.1.0
  basic_utils: ^3.4.0
  intl: ^0.17.0
  shared_preferences: ^2.0.9  
  easy_localization: ^3.0.0
  global_configs: ^1.1.1
  flutter_easyloading: ^3.0.3
  auto_route: ^3.0.4
  equatable: ^2.0.3
  flutter_launcher_icons: ^0.9.2
  cached_network_image: ^3.1.0+1
  url_launcher: ^6.0.15
  pull_to_refresh: ^2.0.0
  animate_do: ^2.0.0
  flutter_staggered_animations: ^1.0.0
  image_picker: ^0.8.1+3
  advance_pdf_viewer_fork: ^2.0.0
  google_fonts: ^3.0.1
  dio: ^4.0.6
  fl_chart: ^0.50.1
  flutter_keyboard_visibility: ^5.2.0
  pattern_formatter: ^2.0.0
  flutter_xlider:
     path: ./modules/flutter_xlider

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^3.0.1
  build_runner: ^2.1.8   
  flutter_lints: ^1.0.4

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/appicon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/svgs/
    - assets/translations/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: SourceSansSemi
      fonts:
        - asset: assets/fonts/source-sans-pro-semi-bold.ttf
    - family: SourceSans
      fonts:
        - asset: assets/fonts/source-sans-pro-light.ttf
          weight: 500
        - asset: assets/fonts/source-sans-pro-semi-bold.ttf
          weight: 600
        - asset: assets/fonts/source-sans-pro-bold.ttf
          weight: 700
          

  


